# Generated by Django 5.1.1 on 2024-10-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendations',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
