# Generated by Django 5.1.1 on 2024-10-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0002_alter_recommendations_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='max_discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='max_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='min_discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='min_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
