# Generated by Django 5.1.1 on 2024-10-07 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0002_alter_profile_last_name_alter_profile_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats',
            name='purchases',
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_brands',
            field=models.ManyToManyField(blank=True, to='botapp.brand'),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_categories',
            field=models.ManyToManyField(blank=True, to='botapp.category'),
        ),
        migrations.AddField(
            model_name='stats',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='botapp.profile'),
        ),
        migrations.CreateModel(
            name='SavedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botapp.profile')),
            ],
        ),
    ]
