# Generated by Django 5.1.1 on 2024-10-07 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0003_remove_stats_purchases_product_stock_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='botapp.product'),
        ),
    ]
