# Generated by Django 5.1.1 on 2024-11-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0004_product_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_merchant_admin',
            field=models.BooleanField(default=False),
        ),
    ]
