# Generated by Django 5.1.1 on 2024-11-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0005_profile_is_merchant_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='brands',
            field=models.ManyToManyField(related_name='merchants', to='botapp.brand'),
        ),
    ]
